//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Final.Models.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class CE_WebEntities : DbContext
    {
        public CE_WebEntities()
            : base("name=CE_WebEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<classMaster> classMasters { get; set; }
        public virtual DbSet<user> users { get; set; }
    
        public virtual ObjectResult<RetrieveClassesForStudent_Result> RetrieveClassesForStudent(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("userId", userId) :
                new ObjectParameter("userId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<RetrieveClassesForStudent_Result>("RetrieveClassesForStudent", userIdParameter);
        }

        public System.Data.Entity.DbSet<Final.Models.ViewModel.ClassMaster> ClassMasters { get; set; }

        public System.Data.Entity.DbSet<Final.Models.ViewModel.UserClasses> UserClasses { get; set; }

        public System.Data.Entity.DbSet<Final.Models.ViewModel.User> Users { get; set; }
    }
}
