//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace inventoryDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITEM
    {
        public int itemNum { get; set; }
        public string itemDescription { get; set; }
        public decimal pricePerItem { get; set; }
        public int quantityOnHand { get; set; }
        public decimal ourCostPerItem { get; set; }
        public Nullable<decimal> valueOfItem { get; set; }
    }
}
